---

- hosts: all
  become: true
  tasks:

  - name: Install apache package
    yum: 
      name: httpd
      state: latest
  
  - name: Start httpd Service  
    ansible.builtin.service:
      name: httpd
      state: started

  - name: Stop firewalld, if started
    ansible.builtin.service:
      name: firewalld
      state: stopped

