---

- hosts: all
  become: true
  tasks:

  - name: Remove apache and nginx package
    package: 
      name: nginx
      state: absent


  - name: Start firewalld, if stopped
    service:
      name: firewalld
      state: started

